# Generated by Django 2.1.7 on 2019-03-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(blank=True, choices=[('1', 'Madame'), ('2', 'Monsieur'), ('3', 'Société')], default='2', max_length=1)),
                ('RaisonSociale', models.CharField(blank=True, max_length=50, null=True)),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=150)),
                ('Addresse', models.TextField(blank=True, null=True)),
                ('Telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.EmailField(blank=True, max_length=200, null=True)),
                ('DateNaissance', models.DateField(blank=True, null=True)),
                ('NumeroPermis', models.CharField(blank=True, max_length=50, null=True)),
                ('DateCreation', models.DateTimeField(blank=True, null=True, verbose_name='Date de création')),
            ],
        ),
    ]
