# Generated by Django 2.1.7 on 2019-03-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partenaire', '0002_auto_20190315_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='DatePermis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='VillePermis',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
