# Generated by Django 2.1.7 on 2019-03-07 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('categorie', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('tarif', models.DecimalField(decimal_places=3, max_digits=15)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('Marque', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('Immatriculation', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Description', models.TextField()),
                ('DatePMEC', models.DateField()),
                ('Couleur', models.CharField(blank=True, max_length=20, null=True)),
                ('NBPortes', models.IntegerField(null=True)),
                ('NbCles', models.IntegerField(null=True)),
                ('DispoVente', models.BooleanField(default=False)),
                ('DispoLocation', models.BooleanField(default=False)),
                ('Archive', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.CharField(blank=True, max_length=20, null=True)),
                ('Marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicule.Marque')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicule.Categorie')),
            ],
        ),
    ]
