# Generated by Django 2.1.7 on 2019-03-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marque',
            name='Favoris',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='marque',
            name='LogoUrl',
            field=models.URLField(null=True),
        ),
    ]
