# Generated by Django 2.1.7 on 2019-03-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0002_auto_20190328_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marque',
            name='LogoUrl',
            field=models.FileField(null=True, upload_to='logo/'),
        ),
    ]
